# Generated by Django 5.1.3 on 2024-12-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('supplier_code', models.CharField(max_length=50)),
                ('weight_per_tray', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trays_per_carton', models.IntegerField()),
                ('carton_type', models.CharField(max_length=100)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('upc_code', models.CharField(max_length=50)),
                ('tray_type', models.CharField(max_length=100)),
                ('shelf_life', models.IntegerField(help_text='Shelf life in days')),
                ('mlor', models.DecimalField(decimal_places=2, help_text='Minimum life on receival', max_digits=10)),
                ('primary_pack_size', models.CharField(max_length=100)),
                ('item_class', models.CharField(max_length=100)),
                ('secondary_label', models.CharField(max_length=255)),
                ('cartons_per_pallet', models.IntegerField()),
                ('item_demand', models.IntegerField(help_text='This is item demand number from Netsuite')),
                ('run_rate', models.DecimalField(decimal_places=2, help_text='This number x 60 x 24 gives number of trays per hour', max_digits=6)),
                ('production_line', models.CharField(choices=[('Production Line 1', 'Production Line 1'), ('Production Line 2', 'Production Line 2'), ('Production Line 3', 'Production Line 3'), ('Production Line 4', 'Production Line 4'), ('Production Line 5', 'Production Line 5'), ('Production Line 6', 'Production Line 6')], max_length=50)),
                ('alternative_production_line', models.CharField(blank=True, choices=[('Production Line 1', 'Production Line 1'), ('Production Line 2', 'Production Line 2'), ('Production Line 3', 'Production Line 3'), ('Production Line 4', 'Production Line 4'), ('Production Line 5', 'Production Line 5'), ('Production Line 6', 'Production Line 6')], max_length=50, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
