# Generated by Django 5.1.3 on 2024-12-01 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='primary_pack_size',
            new_name='primary_pack_weight',
        ),
    ]
